version: "3.9"
services:
  db:
    image: postgres
    container_name: url-db

    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_pass
      POSTGRES_DB: fastapi_db
    ports:
      - "5401:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis

    container_name: url-redis

    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: url-app

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
